#!/usr/bin/env bash

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom Nginx configuration file
echo 'server {
    listen 80 default_server;
    server_name _;

    location / {
        add_header X-Served-By $HOSTNAME;
        proxy_pass http://backend;
    }

    location /status {
        stub_status;
    }
}' | sudo tee /etc/nginx/sites-available/custom_header

# Create a symbolic link to enable the custom configuration
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Remove default configuration if needed
sudo rm /etc/nginx/sites-enabled/default

# Test Nginx configuration and reload
sudo nginx -t
sudo service nginx reload
